from app import app
from flask import render_template


@app.route('/')
@app.route('/index')
def index():
    user = {'nickname': '姜胖'}  # fake user
    posts = [  # fake Array of posts
        {
            'author': {'nickname': 'John'},
            'body': 'Beautiful day in Portland!'
        },
        {
            'author': {'nickname': 'Susan'},
            'body': 'The Avengers movie was so cool!'
        }
    ]
    records = [
        [{"text": "房间号", "value": "静居寺1号"},
         {"text": "时间", "value": "17-07"},
         {"text": "总收入", "value": 1639.00}],
        [{"text": "房间号", "value": "静居寺1号"},
         {"text": "时间", "value": "17-09"},
         {"text": "总收入", "value": 709.00}],
        [{"text": "房间号", "value": "静居寺1号"},
         {"text": "时间", "value": "17-10"},
         {"text": "总收入", "value": 241.00}],
        [{"text": "房间号", "value": "静居寺1号"},
         {"text": "时间", "value": "17-11"},
         {"text": "总收入", "value": 469.00}],
        [{"text": "房间号", "value": "静居寺1号"},
         {"text": "时间", "value": "18-01"},
         {"text": "总收入", "value": 188.00}],
        [{"text": "房间号", "value": "静居寺1号"},
         {"text": "时间", "value": "18-03"},
         {"text": "总收入", "value": 1289.00}],
        [{"text": "房间号", "value": "静居寺1号"},
         {"text": "时间", "value": "18-04"},
         {"text": "总收入", "value": 724.68}],
        [{"text": "房间号", "value": "静居寺1号"},
         {"text": "时间", "value": "18-05"},
         {"text": "总收入", "value": 926.64}],
        [{"text": "房间号", "value": "静居寺1号"},
         {"text": "时间", "value": "18-06"},
         {"text": "总收入", "value": 902.88}],
        [{"text": "房间号", "value": "静居寺1号"},
         {"text": "时间", "value": "18-07"},
         {"text": "总收入", "value": 118.80}],
        [{"text": "房间号", "value": "静居寺2号"},
         {"text": "时间", "value": "17-09"},
         {"text": "总收入", "value": 610.64}],
        [{"text": "房间号", "value": "静居寺2号"},
         {"text": "时间", "value": "17-10"},
         {"text": "总收入", "value": 560.50}],
        [{"text": "房间号", "value": "静居寺2号"},
         {"text": "时间", "value": "17-11"},
         {"text": "总收入", "value": 560.00}],
        [{"text": "房间号", "value": "静居寺2号"},
         {"text": "时间", "value": "17-12"},
         {"text": "总收入", "value": 320.00}],
        [{"text": "房间号", "value": "静居寺2号"},
         {"text": "时间", "value": "18-02"},
         {"text": "总收入", "value": 363.00}],
        [{"text": "房间号", "value": "静居寺2号"},
         {"text": "时间", "value": "18-03"},
         {"text": "总收入", "value": 2001.90}],
        [{"text": "房间号", "value": "静居寺2号"},
         {"text": "时间", "value": "18-04"},
         {"text": "总收入", "value": 764.20}],
        [{"text": "房间号", "value": "静居寺2号"},
         {"text": "时间", "value": "18-06"},
         {"text": "总收入", "value": 76.50}],
        [{"text": "房间号", "value": "静居寺4号"},
         {"text": "时间", "value": "17-07"},
         {"text": "总收入", "value": 60.00}],
        [{"text": "房间号", "value": "静居寺4号"},
         {"text": "时间", "value": "17-08"},
         {"text": "总收入", "value": 760.00}],
        [{"text": "房间号", "value": "静居寺4号"},
         {"text": "时间", "value": "17-09"},
         {"text": "总收入", "value": 1712.00}],
        [{"text": "房间号", "value": "静居寺4号"},
         {"text": "时间", "value": "17-10"},
         {"text": "总收入", "value": 772.00}],
        [{"text": "房间号", "value": "静居寺4号"},
         {"text": "时间", "value": "17-11"},
         {"text": "总收入", "value": 158.00}],
        [{"text": "房间号", "value": "静居寺4号"},
         {"text": "时间", "value": "17-12"},
         {"text": "总收入", "value": 3192.00}],
        [{"text": "房间号", "value": "静居寺4号"},
         {"text": "时间", "value": "18-02"},
         {"text": "总收入", "value": 343.00}],
        [{"text": "房间号", "value": "静居寺4号"},
         {"text": "时间", "value": "18-03"},
         {"text": "总收入", "value": 1645.00}],
        [{"text": "房间号", "value": "静居寺4号"},
         {"text": "时间", "value": "18-04"},
         {"text": "总收入", "value": 1362.00}],
        [{"text": "房间号", "value": "静居寺4号"},
         {"text": "时间", "value": "18-05"},
         {"text": "总收入", "value": 1809.00}],
        [{"text": "房间号", "value": "静居寺4号"},
         {"text": "时间", "value": "18-06"},
         {"text": "总收入", "value": 989.00}],
        [{"text": "房间号", "value": "静居寺4号"},
         {"text": "时间", "value": "18-07"},
         {"text": "总收入", "value": 637.00}],
        [{"text": "房间号", "value": "静居寺5号"},
         {"text": "时间", "value": "17-07"},
         {"text": "总收入", "value": 1650.00}],
        [{"text": "房间号", "value": "静居寺5号"},
         {"text": "时间", "value": "17-08"},
         {"text": "总收入", "value": 784.00}],
        [{"text": "房间号", "value": "静居寺5号"},
         {"text": "时间", "value": "17-09"},
         {"text": "总收入", "value": 900.00}],
        [{"text": "房间号", "value": "静居寺5号"},
         {"text": "时间", "value": "17-10"},
         {"text": "总收入", "value": 1141.50}],
        [{"text": "房间号", "value": "静居寺5号"},
         {"text": "时间", "value": "17-12"},
         {"text": "总收入", "value": 443.52}],
        [{"text": "房间号", "value": "静居寺5号"},
         {"text": "时间", "value": "18-03"},
         {"text": "总收入", "value": 793.65}],
        [{"text": "房间号", "value": "静居寺5号"},
         {"text": "时间", "value": "18-04"},
         {"text": "总收入", "value": 547.10}],
        [{"text": "房间号", "value": "静居寺5号"},
         {"text": "时间", "value": "18-05"},
         {"text": "总收入", "value": 130.00}],
        [{"text": "房间号", "value": "静居寺5号"},
         {"text": "时间", "value": "18-06"},
         {"text": "总收入", "value": 1050.00}],
        [{"text": "房间号", "value": "静居寺5号"},
         {"text": "时间", "value": "18-07"},
         {"text": "总收入", "value": 637.50}]
    ]

    return render_template('index.html', title='Home', user=user, posts=posts, records=records)
